# Generated by Django 4.2.8 on 2025-05-29 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название экзамена')),
                ('min_score', models.IntegerField(verbose_name='Минимальный балл')),
                ('max_score', models.IntegerField(verbose_name='Максимальный балл')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'db_table': 'exams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название факультета')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'db_table': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('code', models.CharField(max_length=50, verbose_name='Код направления')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='statements.faculty')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'db_table': 'directions',
                'ordering': ['faculty', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='draft', max_length=20)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.direction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательный экзамен')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.direction')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.exam')),
            ],
            options={
                'verbose_name': 'Экзамен направления',
                'verbose_name_plural': 'Экзамены направлений',
                'db_table': 'direction_exams',
                'ordering': ['direction', 'exam'],
                'indexes': [models.Index(fields=['direction'], name='direction_exam_direction_idx'), models.Index(fields=['exam'], name='direction_exam_exam_idx')],
                'unique_together': {('direction', 'exam')},
            },
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['code'], name='direction_code_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['direction'], name='application_direction_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'direction')},
        ),
    ]
