# Generated by Django 4.2.8 on 2025-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('approved', 'Принято'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
