# Generated by Django 4.2.8 on 2025-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Черновик', max_length=20),
        ),
    ]
