# Generated by Django 4.2.8 on 2025-05-29 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX', max_length=20, verbose_name='Телефон')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('birth_cert', 'Свидетельство о рождении')], default='passport', max_length=20, verbose_name='Тип документа')),
                ('doc_series', models.CharField(blank=True, max_length=10, verbose_name='Серия документа')),
                ('doc_number', models.CharField(blank=True, max_length=20, verbose_name='Номер документа')),
                ('dormitory_needed', models.BooleanField(default=False, verbose_name='Требуется общежитие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profiles',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['phone'], name='profile_phone_idx'), models.Index(fields=['doc_series', 'doc_number'], name='profile_doc_idx'), models.Index(fields=['dormitory_needed'], name='profile_dormitory_idx')],
            },
        ),
    ]
